#!/usr/bin/env bash

num="$(i3-msg -t get_workspaces | jq '.[]|select(.focused==true).num')"
echo "num: $num"
name="$(dmenu -p "Rename: " < /dev/null)"
echo "name: $name"

if [ "$name" == "" ]; then
  i3-msg "rename workspace to $num"
else
  i3-msg "rename workspace to $num:$name"
fi
